# Generated by Django 3.0.2 on 2020-03-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_title', models.CharField(max_length=32)),
                ('i_content', models.CharField(max_length=200)),
                ('i_tag', models.CharField(max_length=128, null=True)),
                ('i_p_id', models.CharField(max_length=32)),
                ('i_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=32)),
                ('u_pwd', models.CharField(max_length=32)),
            ],
        ),
    ]
