# Generated by Django 3.0.2 on 2020-05-08 01:23

from django.db import migrations, models
import django.db.models.deletion
import main.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_title', models.CharField(max_length=32)),
                ('i_content', models.CharField(max_length=200)),
                ('i_tag', models.CharField(max_length=128, null=True)),
                ('i_p_id', models.CharField(max_length=32)),
                ('i_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=32)),
                ('u_pwd', models.CharField(max_length=32)),
                ('u_ico', models.ImageField(default='userIco\\default_ico\\default.jpeg', null=True, storage=main.storage.ImageStorage(), upload_to='userIco/%Y/%m/%d/')),
                ('u_nname', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(storage=main.storage.ImageStorage(), upload_to='itemPic/%Y/%m/%d/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
            ],
        ),
    ]
