# Generated by Django 3.0.2 on 2020-05-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('i_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likers', to='main.Item')),
                ('u_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedItems', to='main.User')),
            ],
        ),
    ]
