# Generated by Django 3.0.2 on 2020-04-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='i_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
