# Generated by Django 3.0.2 on 2020-05-13 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200513_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='i_like_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='i_remark_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='i_p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='main.User'),
        ),
    ]
