# Generated by Django 3.0.2 on 2020-05-08 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_like', models.IntegerField(default=0)),
                ('R_remark_num', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('R_content', models.TextField(max_length=500)),
                ('R_Po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='RemarkI',
            fields=[
                ('baseremark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='remarksys.BaseRemark')),
                ('R_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item')),
            ],
            options={
                'ordering': ['-time'],
            },
            bases=('remarksys.baseremark',),
        ),
        migrations.CreateModel(
            name='RemarkR',
            fields=[
                ('baseremark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='remarksys.BaseRemark')),
                ('R_remark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remarksys.RemarkI')),
                ('R_replay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='remarksys.RemarkR')),
            ],
            options={
                'ordering': ['time'],
            },
            bases=('remarksys.baseremark',),
        ),
    ]
