# Generated by Django 3.0.2 on 2020-05-11 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remarksys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remarkr',
            name='R_remark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RemarkI', to='remarksys.RemarkI'),
        ),
    ]
