# Generated by Django 3.0.2 on 2020-05-11 02:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('remarksys', '0004_auto_20200511_0236'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='remarki',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='remarkr',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
