# Generated by Django 3.0.2 on 2020-05-11 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remarksys', '0005_auto_20200511_0250'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='remarkr',
            managers=[
            ],
        ),
    ]
