# Generated by Django 3.0.2 on 2020-05-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remarksys', '0006_auto_20200511_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseremark',
            name='R_Po_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='remarkr',
            name='R_replay_to_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
